import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Noetherian.Defs
import Mathlib.RingTheory.Nullstellensatz

/-!
# Zero loci on a finite grid

Let `K` be a field, `σ` a finite type and `A : σ → Finset K`. We study the zero locus of an ideal
of `MvPolynomial σ K` restricted to the finite grid `∏ i, A i`, and compute its vanishing ideal.

## Main definitions

* `MvPolynomial.zeroLocusOn A I`: the set `V^A(I) = {x ∈ A^n | p(x) = 0 for all p ∈ I}`, as a
  `Finset`.
* `MvPolynomial.zeroLocusOn_compl A I`: the points of the grid `A^n` that are not in `V^A(I)`.

## Main results

* `MvPolynomial.vanishingIdeal_zeroLocus_eq_ideal_sum`: the vanishing ideal of `V^A(I)` is
  `I + vanishingIdeal K A^n`.

## Implementation notes

The proof of the main result picks a finite generating set `S` of `I` (`I` is Noetherian). For each
point `b` of the grid outside `V^A(I)` we choose a generator `j_b ∈ S` with `j_b(b) ≠ 0`. The
polynomial `∏ b, (j_b - j_b(b))` vanishes outside `V^A(I)` and is a nonzero constant modulo `I`.
-/

noncomputable section

namespace MvPolynomial

variable {K σ : Type*} [Field K] [Fintype σ]

section ZeroLocusOn

variable (A : σ → Finset K) (I : Ideal (MvPolynomial σ K))

open scoped Classical in
/-- The variety `V^A(I) = {x ∈ A^n | p(x) = 0, ∀ p ∈ I}`. -/
def zeroLocusOn : Finset (σ → K) :=
  {x ∈ Fintype.piFinset A | x ∈ zeroLocus K I}

open scoped Classical in
/-- The points of the grid `A^n` that do not lie in `zeroLocusOn A I`. -/
def zeroLocusOn_compl : Finset (σ → K) :=
  {x ∈ Fintype.piFinset A | x ∉ zeroLocus K I}

variable {A I}

@[simp]
theorem mem_zeroLocusOn {x : σ → K} :
    x ∈ zeroLocusOn A I ↔ (∀ i, x i ∈ A i) ∧ x ∈ zeroLocus K I := by
  simp [zeroLocusOn]

@[simp]
theorem mem_zeroLocusOn_compl {x : σ → K} :
    x ∈ zeroLocusOn_compl A I ↔ (∀ i, x i ∈ A i) ∧ x ∉ zeroLocus K I := by
  simp [zeroLocusOn_compl]

end ZeroLocusOn

section VanishingPoly

variable {A : σ → Finset K} {I : Ideal (MvPolynomial σ K)}
variable (S : Finset (MvPolynomial σ K)) (hI : I = Ideal.span S)

include hI

/-- If `I` is generated by the finite set `S` and `x ∈ zeroLocusOn_compl A I`, then some generator
`p ∈ S` does not vanish at `x`. -/
private lemma exists_mem_eval_ne_zero_of_mem_zeroLocusOn_compl {x : σ → K}
    (hx : x ∈ zeroLocusOn_compl A I) : ∃ p ∈ S, eval x p ≠ 0 := by
  simp [hI] at hx ⊢
  obtain ⟨_, g, hg, hgx⟩ := hx
  induction hg using Submodule.span_induction with
  | mem p hp => exact ⟨p, hp, hgx⟩
  | zero => aesop
  | add p₁ p₂ _ _ ih₁ ih₂ =>
    simp at hgx
    by_cases h : eval x p₁ = 0
    · simp [h] at hgx
      exact ih₂ hgx
    · exact ih₁ h
  | smul p₁ p₂ _ ih =>
    by_cases h : eval x p₂ = 0
    · simp [h] at hgx
    · exact ih h

/-- A generator `j_x ∈ S` of `I` with `j_x(x) ≠ 0`, for `x ∈ zeroLocusOn_compl A I`. -/
private def nonvanishingGen {x : σ → K} (hx : x ∈ zeroLocusOn_compl A I) : MvPolynomial σ K :=
  Classical.choose (exists_mem_eval_ne_zero_of_mem_zeroLocusOn_compl S hI hx)

private lemma nonvanishingGen_mem {x : σ → K} (hx : x ∈ zeroLocusOn_compl A I) :
    nonvanishingGen S hI hx ∈ S :=
  (Classical.choose_spec (exists_mem_eval_ne_zero_of_mem_zeroLocusOn_compl S hI hx)).1

private lemma eval_nonvanishingGen_ne_zero {x : σ → K} (hx : x ∈ zeroLocusOn_compl A I) :
    eval x (nonvanishingGen S hI hx) ≠ 0 :=
  (Classical.choose_spec (exists_mem_eval_ne_zero_of_mem_zeroLocusOn_compl S hI hx)).2

variable (A) in
/-- The polynomial `∏ b ∈ zeroLocusOn_compl A I, (j_b - j_b(b))`, which vanishes on every point of
`zeroLocusOn_compl A I`. -/
private def vanishingPoly : MvPolynomial σ K :=
  ∏ b ∈ (zeroLocusOn_compl A I).attach,
    (nonvanishingGen S hI b.prop - C (eval (b : σ → K) (nonvanishingGen S hI b.prop)))

variable (A) in
/-- The constant `∏ b ∈ zeroLocusOn_compl A I, -j_b(b)`. -/
private def vanishingConst : K :=
  ∏ b ∈ (zeroLocusOn_compl A I).attach, -eval (b : σ → K) (nonvanishingGen S hI b.prop)

private lemma eval_vanishingPoly_eq_zero {x : σ → K} (hx : x ∈ zeroLocusOn_compl A I) :
    eval x (vanishingPoly A S hI) = 0 := by
  rw [vanishingPoly, eval_prod, Finset.prod_eq_zero_iff]
  refine ⟨⟨x, hx⟩, Finset.mem_attach _ _, ?_⟩
  simp

variable (A) in
private lemma vanishingConst_ne_zero : vanishingConst A S hI ≠ 0 := by
  rw [vanishingConst, Finset.prod_ne_zero_iff]
  intro b _
  exact neg_ne_zero.mpr (eval_nonvanishingGen_ne_zero S hI b.prop)

variable (A) in
private lemma exists_mem_vanishingPoly_eq_C_add :
    ∃ h ∈ I, vanishingPoly A S hI = C (vanishingConst A S hI) + h := by
  classical
  rw [vanishingConst, vanishingPoly]
  induction (zeroLocusOn_compl A I).attach using Finset.induction_on with
  | empty =>
    refine ⟨0, Ideal.zero_mem I, ?_⟩
    rw [Finset.prod_empty, Finset.prod_empty]
    simp
  | insert a B ha ih =>
    -- Let `a ∈ zeroLocusOn_compl A I` and `B ⊆ zeroLocusOn_compl A I` with `a ∉ B`.
    -- Suppose there is `g ∈ I` with `∏ b ∈ B, (j_b - j_b(b)) = (∏ b ∈ B, -j_b(b)) + g`.
    obtain ⟨g, g_mem, ih⟩ := ih
    let ja := nonvanishingGen S hI a.prop
    let ca : MvPolynomial σ K := C (eval (a : σ → K) ja)
    let c := ∏ b ∈ B, -eval (b : σ → K) (nonvanishingGen S hI b.prop)
    refine ⟨ja * C c + ja * g - ca * g, ?_, ?_⟩
    -- The polynomial lies in the ideal.
    · apply Ideal.sub_mem
      · apply Ideal.add_mem
        · apply Ideal.mul_mem_right
          rw [hI]
          exact Ideal.subset_span (nonvanishingGen_mem S hI a.prop)
        · apply Ideal.mul_mem_left
          exact g_mem
      · apply Ideal.mul_mem_left
        exact g_mem
    -- The identity.
    · rw [Finset.prod_insert ha, ih, Finset.prod_insert ha]
      grind

variable (A) in
private lemma exists_mem_eq_mul_vanishingPoly_add (p : MvPolynomial σ K) :
    ∃ c : K, ∃ h ∈ I, p = p * vanishingPoly A S hI * C c + h := by
  obtain ⟨g, g_mem, hg⟩ := exists_mem_vanishingPoly_eq_C_add A S hI
  let c := (vanishingConst A S hI)⁻¹
  refine ⟨c, -p * g * C c, ?_, ?_⟩
  · apply Ideal.mul_mem_right
    apply Ideal.mul_mem_left
    exact g_mem
  · simp [hg, c]
    ring_nf
    simp [mul_assoc, ← C_mul, vanishingConst_ne_zero]

end VanishingPoly

/-- The vanishing ideal of `V^A(I)` is the sum of `I` and the vanishing ideal of the grid `A^n`. -/
theorem vanishingIdeal_zeroLocus_eq_ideal_sum
    (A : σ → Finset K) (I : Ideal (MvPolynomial σ K)) :
    vanishingIdeal K (zeroLocusOn A I : Set (σ → K)) =
      I + vanishingIdeal K {x | ∀ i, x i ∈ A i} := by
  ext p
  simp [zeroLocusOn, Submodule.mem_sup]
  constructor <;> intro hp
  · obtain ⟨S, hS⟩ := Ideal.fg_of_isNoetherianRing I
    obtain ⟨c, g, g_mem, hg⟩ := exists_mem_eq_mul_vanishingPoly_add A S hS.symm p
    use g, g_mem
    use p * vanishingPoly A S hS.symm * C c
    constructor
    · intro x hx
      rw [eval_mul]
      by_cases hx' : x ∈ zeroLocusOn A I
      · simp at hx'
        obtain ⟨_, hxI⟩ := hx'
        specialize hp x hx hxI
        simp [hp]
      · have xin : x ∈ zeroLocusOn_compl A I := by
          simp at hx' ⊢
          exact ⟨hx, hx' hx⟩
        have := eval_vanishingPoly_eq_zero S hS.symm xin
        simp [this]
    · grind
  · intro x hx hx'
    -- Let `p = f + g`, where `f ∈ I` and `g ∈ vanishingIdeal K {x | ∀ i, x i ∈ A i}`.
    obtain ⟨f, hf, g, hg, hp⟩ := hp
    rw [← hp, eval_add]
    specialize hx' f hf
    specialize hg x hx
    simp [hx', hg]

end MvPolynomial
